name: apple build

on: [push, pull_request]

jobs:

  apple-mobile:
    if: github.event_name == 'pull_request' || endsWith( github.event.head_commit.message, '[run ci]' )
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [OS64, TVOS]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate project
        run: cmake -B build --toolchain .CMake/apple.cmake -DOQS_USE_OPENSSL=OFF -DPLATFORM=${{ matrix.platform }} .
      - name: Build project
        run: cmake --build build
